# Generated by Django 4.0 on 2023-05-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
