# Generated by Django 4.0 on 2023-05-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_fono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fono',
            new_name='phone',
        ),
    ]
