# Generated by Django 4.0 on 2023-05-24 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_usermanagement', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(choices=[('CHIHUAHUA', 'CHIHUAHUA'), ('DOBERMAN', 'DOBERMAN'), ('BORDER COLLIE', 'BORDER COLLIE'), ('GOLDEN RETRIVER', 'GOLDEN RETRIVER'), ('FRENCH POOL', 'FRENCH POOL'), ('FOX TERRIER', 'FOX TERRIER'), ('DALMATA', 'DALMATA'), ('COMÚN', 'COMÚN')], default='CHIHUAHUA', max_length=30)),
                ('photo', models.ImageField(blank=True, default='/dog/dog_avatar.png', null=True, upload_to='')),
                ('dog_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_usermanagement.customuser')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
