# Generated by Django 4.2.1 on 2023-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(choices=[('CHIHUAHUA', 'CHIHUAHUA'), ('DOBERMAN', 'DOBERMAN'), ('BORDER COLLIE', 'BORDER COLLIE'), ('GOLDEN RETRIVER', 'GOLDEN RETRIVER'), ('FRENCH POOL', 'FRENCH POOL'), ('FOX TERRIER', 'FOX TERRIER'), ('DALMATA', 'DALMATA'), ('COMÚN', 'COMÚN')], default='CHIHUAHUA', max_length=30)),
                ('photo', models.ImageField(blank=True, default='/dog/dog_avatar.png', null=True, upload_to='')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
