# Generated by Django 4.0 on 2023-05-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_usermanagement', '0001_initial'),
        ('apps_dog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_usermanagement.customuser'),
        ),
    ]
