# Generated by Django 4.2.1 on 2023-05-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
