# Generated by Django 4.2.1 on 2023-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_usermanagement', '0002_rename_is_delete_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_pet_sitter',
            field=models.BooleanField(null=True),
        ),
    ]
