# Generated by Django 4.0 on 2023-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost_hour',
            field=models.IntegerField(default=0),
        ),
    ]
