# Generated by Django 4.0 on 2023-06-01 18:22

import apps.reservation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_dog', '0001_initial'),
        ('user', '0008_auto_20230601_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_reservations', to='apps_dog.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reservations', to='user.user', validators=[apps.reservation.models.validate_owner])),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitter_reservations', to='user.user', validators=[apps.reservation.models.validate_sitter])),
            ],
        ),
    ]
