# Generated by Django 4.0 on 2023-06-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reservation', '0002_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
